language: ruby
rvm:
- 2.2.5
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: Ze75mFqxKH67Zw+vMpVj5lQOPrKbqDHn7q1cv8cxXtxHjsFMJ2AvoVmkNVs7xyTrB/mTNsI3GBO/taIqbBpB+bqvytKHAzXM5b+XAq+s+hsnkNB43LpegXeTUSCHRflFHCXi8EaXp1/3rzwt72nYubgi7EhI4SGJhuvDnLMtHyzYspXm5eMfOw3WNeOgz8Fo0cSkdP5Zms+r2veynub7UBKXBIjiAssLMHGtDHhjwzOF+bm3uvQxHvY9FWKplUv70AWQDk1/V+FxBtXRYWRPlQK2q+B/UL8LUZPLdVqZJnWXn8pePgeU6Dhgz5mgdrOmCR87/0Y3177xhd4MbwNJWeZAC4A2Df1680fMV7xBb3fdl1NcZO5/k8xDVA8yiFIUutQ6gLyLeSEnIAIVgtbmmx1U0lx0cKyqHOE2Kowe9/nio8SugfQ77H3xl9kxkPUcrZGU0dcHCfBn8NsUu4vq2VMrGfvtuIYU0zLk/raj/aJRwyaYcdT3yhXBSlskV/cMNFqGYmvmnJffE7d+59UhJVVCyN8xYA+OR6oI/CbvVPGkUB2uWjfs28MHXP2fXCM6KdpdjNa30kcl6eAmGMTBfVVid1oqJehUxSps1zSj2usA0ipujWHSb/dlAfexXZhTUBNk5zrg694KiTc/hdQAklyO+Hy6YB3sJTWjlN8Mryw=
