= Code of Conduct
:page-title: Virtual JUG
:page-description: The Virtual JUG's website and blog
:icons: font
:showtitle:

{nbsp} +

All attendees, speakers, sponsors and volunteers in our community are required to agree with the following code of conduct. Organisers will enforce this code throughout the event. We are expecting cooperation from all participants to help ensuring a safe environment for everybody.

== The Quick Version
{nbsp} +
Our community is dedicated to providing a harassment-free community experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of community participants in any form. Sexual language and imagery is not appropriate for any community, including talks, workshops, Twitter and other online media. Anyone violating these rules may be sanctioned or expelled from the community and chatrooms at the discretion of the community organisers.

== The Less Quick Version
{nbsp} +
Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, technology choices, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

Participants asked to stop any harassing behavior are expected to comply immediately.

Sponsors are also subject to the anti-harassment policy. In particular, sponsors should not use sexualized images, activities, or other material. Booth staff (including volunteers) should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized environment.

If a participant engages in harassing behavior, the community organisers may take any action they deem appropriate, including warning the offender or expulsion from the community

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of vJUG staff immediately.
